# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cff91473c545768937ceada246dd4e15c3b586bf263f51fe59f85565bf29e61bd627d1dc1ea664efe1e4af9c9d2a050ce199eae0604eeeaf7dd585125be944a

test:
  secret_key_base: 12c72cbb51cccd42c7dbdb9719eab3d7366ac389d132006642a1e61c2db7a268d071020307f20942f2c9399bb7646e53594c99f93945c4e611ce56a1cba19c8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
